name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true 

      - name: Install dependencies
        run: |
          brew update
          brew install llvm ninja

      - name: Update PATH for LLVM
        run: echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH

      - name: Check Clang tools versions
        run: |
          clang++ --version
          clang-tidy --version
          clang-format --version

      - name: Prepare build directory
        run: |
          rm -rf build
          mkdir build

      - name: Run Clang Tidy
        run: |
          clang-tidy src/*.cpp -- -Iinclude -std=c++20

      - name: Run Clang Format
        run: |
          find src tests include -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror

      - name: Build the project
        run: |
            cd build
            cmake -G Ninja ..
            ninja

      - name: Run Tests
        run: |
          cd build
          ./multithreaded_generator_tests